config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'items/new'
  post 'items/new', action: :create, controller: 'items'
  get 'items', action: :index, controller: 'items'
  delete 'items/:id', action: :destroy, controller: 'items'
  get 'items/:id/edit', action: :edit, controller: 'items'
  patch 'items/:id', action: :update, controller: 'items'
  put 'items/:id', action: :update, controller: 'items'

  root 'items#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  validates :key, :value, presence: true
  validates :key, :value, format: { with: /\A[a-zA-Z]+\z/ }
  scope :search_by_key, ->(query) { where('key ilike ?', "%#{query}%") }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:destroy, :edit, :update]

  def index
    @items = Item.all
    if params[:search_by_key]
      @items = Item.search_by_key(params[:search_by_key])
    else
      @items = Item.all
    end
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to action: 'index'
    else
      render :new
    end
  end

  def edit
  end

  def update
    @item.update(item_params)
    redirect_to action: 'index'
  end

  def destroy
    @item.destroy
    redirect_to action: 'index'
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.permit(:key, :value)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/edit.html.erb
<h1>Edit Form</h1>

<%= form_with(url: "/items/#{@item.id}", method: "patch") do %>
    <div class="field">
        <%= label_tag(:key) %>
        <%= text_field_tag(:key) %>
    </div>
    <div class="field">
        <%= label_tag(:value) %>
        <%= text_field_tag(:value) %>
    </div>
    <div class="actions">
        <%= submit_tag('Update') %>
    </div>
<% end %>
<%= link_to 'Back', '/items' %>

app/views/items/index.html.erb
<%= form_tag(items_path, :method => :get) do %>
  <p>
    <%= text_field_tag :search_by_key, params[:search_by_key] %>
    <%= submit_tag 'Search' %>
  </p>
<% end %>

<table>
    <thead>
        <tr>
            <th>Key</th>
            <th>Value</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <% @items.each do |item| %>
            <tr>
                <td><%= item.key %></td>
                <td><%= item.value %></td>
                <td><%= link_to 'Edit', "/items/#{item.id}/edit" %></td>
                <td><%= link_to 'Delete', "/items/#{item.id}", method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
        <% end %>
    </tbody>
</table>

<%= link_to 'Add a new item!', items_new_path, class: 'btn-click-here' %>

app/views/items/new.html.erb
<h1>New Item Form</h1>

<%= form_with(local: true) do |form| %>
    <% if @item.errors.any? %>
        <ul>
            <% @item.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    <% end %>

    <div class="field">
        <%= form.label :key %>
        <%= form.text_field :key %>
    </div>
    <div class="field">
        <%= form.label :value %>
        <%= form.text_field :value %>
    </div>
    <div class="actions">
        <%= form.submit 'Add' %>
    </div>

<% end %>
<%= link_to 'Back', '/items' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MemoryAppRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>